apiVersion: apps/v1
kind: Deployment
metadata:
  name: 11frankgallovg
  namespace: fase-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
