apiVersion: v1
kind: Service
metadata:
  name: usuario-service
  namespace: fase-1
spec:
  selector:
    app: nginx
  ports:
    - protocol: 30002
      port: 8080
      targetPort: 8080
  type: ClusterIP
