apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: 11frankgallo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frankgallosanchez23/react-dockerized-app:v3.0
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BACKEND
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: VITE_API_BACKEND