apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: 11frankgallo
spec:
  selector:
    app: frontend
  ports:
    - port: 30003       # Puerto que el Service expondrá
      targetPort: 5173  # Puerto en el contenedor donde tu aplicación escucha
      nodePort: 30003   # Puerto asignado en el nodo
  type: NodePort       # Esto hace accesible el Front-End desde fuera del cluster